// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUrl(ctx context.Context, arg CreateUrlParams) (Urls, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteUrl(ctx context.Context, id int64) error
	GetUrlById(ctx context.Context, id int64) (Urls, error)
	GetUrlByShort(ctx context.Context, shortUrl string) (Urls, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	IncrementClick(ctx context.Context, id int64) error
	ListUserUrls(ctx context.Context, arg ListUserUrlsParams) ([]Urls, error)
	UpdateOrgUrl(ctx context.Context, arg UpdateOrgUrlParams) (Urls, error)
}

var _ Querier = (*Queries)(nil)
